---
title: "About me"
description: |
---

## Resumé

I hold a DSc in Plant Pathology (Univ. Federal de Pelotas, 2004) with 2-year PostDoc training in risk assessment and prediction (Yang Lab, Iowa State University). Currently, I am Associate Professor at the Universidade Federal de Viçosa (UFV) where I have both teaching and mentoring (masters and doctorate) responsibilities. You can get access to my peer-reviewed publications in my academic profiles: [ORCID, publons, Google Scholar, ResearchGate](https://orcid.org/0000-0003-4398-409Xhttps://www.researchgate.net/profile/Emerson_Del_Ponte).

## Research

I am associate Professor leading a research Laboratory focused on thestudy of plant disease epidemics. We make use of statistical and mathematical models as well as field, greenhouse and laboratory experimental work.

The **computational work** is non pathogen-specific and covers a broader range of topics in plant disease epidemiology, including: 1) assessment of disease intensity and crop loss; 2) modeling temporal progress and spatial spread across scales; 3) assessment and prediction of disease risk, and 3) conducting systematic reviews and meta-analysis.

The **experimental researc**h is focused on genotyping and phenotyping of fungal pathogen populations. These include assessment of several traits such as: reproduction, pathogenicity, aggressiveness, toxigenic potential and fungicide resistance. Currently, we study two of the most dangerous plant pathogens worlwide: mycotoxigenic *Fusarium* that cause head blights or ear rots in winter and summer crops and *Pyricularia* blast of rice, wheat and grasses.

## Services

I've been involved in scholarly peer-review since early in my career. I've served as Associate Editor for a few journals, including Plant Disease. Currently, I am Editor in Chief for [Tropical Plant Pathology](www.sbfitopatologia.org.br/tpp), the journal of the [Brazilian Phytopathological Society](www.sbfitopatologia.org.br).

## Open Science

I strongly advocate for an open and reproducible research model and culture that may ultimate contribute to a more accessible, transparent and reliable science. This led me to co-found [Open Plant Pathology](http://www.openplantpathology.org/) Initiative together with [Adam Sparks](http://adamhsparks.com). In my Lab, we make use of [R language](https://www.r-project.org/) and [Tidyverse](https://www.tidyverse.org/) for all statistical and data science related activities. All data and computational codes produced during our research are made available ahead of peer-review. You can find our code on [GitHub](https://github.com/emdelponte). The research outcomes are organized and shared as a [research compendium](https://research-compendium.science/) and [preprints](https://publicationethics.org/resources/discussion-documents/preprints) of manuscripts are archived in Open Science Framework ([OSF](https://osf.io/jb6yd)).
