---
title: "My Lab"
description: |
---

## Our Research

We make use of statistical and mathematical models as well as field, greenhouse and laboratory experimental work to measure, understand, compare and predict plant disease epidemics.

The **computational work** is non pathogen-specific and covers a broad range of topics in plant disease epidemiology, including:

-   Assessment of disease intensity and crop loss

-   Modeling temporal progress and spatial spread across scales

-   Assessment and prediction of disease risk

-   Conducting systematic reviews and meta-analysis

The **experimental researc**h is focused on genotyping and phenotyping of fungal pathogen populations. These include assessment of several traits such as: reproduction, pathogenicity, aggressiveness, toxigenic potential and fungicide resistance. Currently, we study two of the most dangerous plant pathogens worldwide: mycotoxigenic *Fusarium* that cause head blights or ear rots in winter and summer crops and *Pyricularia* blast of rice, wheat and grasses.

## Members

[Gustavo B. dos Santos](https://www.linkedin.com/in/gustavo-bilibio-dos-santos-a85206140/?originalSubdomain=br) (M)\
[Kaíque dos Santos Alves](https://twitter.com/AlvesKS_) (M, D)\
[Jhonatan Paulo Barro](https://twitter.com/jhonatan_barro) (M, D)\
[Ignácio Cazón](https://twitter.com/li_cazon) (D)

## Former members

### UFV

[João Paulo Ascari](https://twitter.com/Joao_P_Ascari) (D)\
[Sheila M. P. Andrade](https://twitter.com/sheilaandrade46) (M)\
[Maíra R. Duffeck](https://twitter.com/MahDuffeck) (M, D)\
[Franklin J. Machado](http://www.dfp.ufv.br/departamento/docentes/franklin-jackson-machado/) (M, D)\
Caroline F. Ávila (M)\

### UFRGS

[Paulo R. Kuhnem](https://www.linkedin.com/in/paulo-roberto-kuhnem-junior-81871b7a/?originalSubdomain=br) (D)\
Larissa B. Gomes (M)\
[Camila P. Nicolli](https://scholar.google.com/citations?hl=en&user=oRAnEDgAAAAJ&view_op=list_works&sortby=pubdate) (M)\
[Leilane S. D'Ávila](https://scholar.google.com.br/citations?hl=pt-BR&user=SX5_arwAAAAJ&view_op=list_works&sortby=pubdate) (M)\
[Felipe Dalla Lana](https://twitter.com/felipedallalana?lang=en) (M)\
André A. Schwanck (M)\
Raquel Stumpf (M)\
[Paula Astolfi](https://www.linkedin.com/in/paula-astolfi-a0540330/?originalSubdomain=br) (M)\
[Piérri Spolti](https://twitter.com/SpoltiPierri?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)(M, D)
